name: Build and push multi-arch images

on:
  pull_request:
    branches: master
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up multi-arch builds
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v2
        with:
          buildx-version: latest
          skip-cache: false
          qemu-version: latest

      - name: Login to hub
        run: echo "${{ secrets.TOKEN }}" | docker login -u "${{ secrets.NAME }}" --password-stdin

      - name: Build and push
        run: |
          docker buildx build --platform linux/amd64,linux/arm64/v8,linux/arm/v7,linux/ppc64le,linux/s390x -t nadavtasher/dockervisor:latest dockervisor --push
